name: test

on:
  push:
    branches:
      - main

jobs:
  longlong:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: max ENV length
        run: getconf ARG_MAX
      - name: Echo $GITHUB_STEP_SUMMARY
        run: echo $GITHUB_STEP_SUMMARY
      - name: Adding markdown
        run: cat checkbox.md >> $GITHUB_STEP_SUMMARY
